// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJ_SfbajGwnMfRKGtLKnH-O64RPnSR_U',
    appId: '1:452828295167:web:8a52bcdf99ca2f0feb81ca',
    messagingSenderId: '452828295167',
    projectId: 'restaurant-order-b2a86',
    authDomain: 'restaurant-order-b2a86.firebaseapp.com',
    storageBucket: 'restaurant-order-b2a86.appspot.com',
    measurementId: 'G-564EBGXEMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwkLW-jpLuoBmsyj5GSv8T_E8hA-rvfI',
    appId: '1:452828295167:android:8a30e6269d5a207ceb81ca',
    messagingSenderId: '452828295167',
    projectId: 'restaurant-order-b2a86',
    storageBucket: 'restaurant-order-b2a86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Mb5f2bOWZV-dmCvK69Bh3aD64vJJDwE',
    appId: '1:452828295167:ios:618a4218ef487109eb81ca',
    messagingSenderId: '452828295167',
    projectId: 'restaurant-order-b2a86',
    storageBucket: 'restaurant-order-b2a86.appspot.com',
    iosClientId: '452828295167-lhkgfs20eo9i9qg1cb5fo9n68s3lj263.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantOrder',
  );
}
